
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORENTREDECIMAL ENTERO ENTRE IGNORAR MAS MENOS PARENT_A PARENT_C POR\n        calculo : expresion\n                | vacio\n        \n        expresion : ENTERO\n                | DECIMAL\n        \n        expresion : expresion POR expresion\n                | expresion ENTRE expresion\n                | expresion MAS expresion\n                | expresion MENOS expresion\n        \n        expresion : PARENT_A expresion PARENT_C\n        \n        vacio : \n        '
    
_lr_action_items = {'ENTERO':([0,6,7,8,9,10,],[4,4,4,4,4,4,]),'DECIMAL':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'PARENT_A':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([0,1,2,3,4,5,12,13,14,15,16,],[-10,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,]),'POR':([2,4,5,11,12,13,14,15,16,],[7,-3,-4,7,-5,-6,7,7,-9,]),'ENTRE':([2,4,5,11,12,13,14,15,16,],[8,-3,-4,8,-5,-6,8,8,-9,]),'MAS':([2,4,5,11,12,13,14,15,16,],[9,-3,-4,9,-5,-6,-7,-8,-9,]),'MENOS':([2,4,5,11,12,13,14,15,16,],[10,-3,-4,10,-5,-6,-7,-8,-9,]),'PARENT_C':([4,5,11,12,13,14,15,16,],[-3,-4,16,-5,-6,-7,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calculo':([0,],[1,]),'expresion':([0,6,7,8,9,10,],[2,11,12,13,14,15,]),'vacio':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calculo","S'",1,None,None,None),
  ('calculo -> expresion','calculo',1,'p_calculo','main.py',85),
  ('calculo -> vacio','calculo',1,'p_calculo','main.py',86),
  ('expresion -> ENTERO','expresion',1,'p_expresion_ENTERO_DECIMAL','main.py',101),
  ('expresion -> DECIMAL','expresion',1,'p_expresion_ENTERO_DECIMAL','main.py',102),
  ('expresion -> expresion POR expresion','expresion',3,'p_expresion','main.py',108),
  ('expresion -> expresion ENTRE expresion','expresion',3,'p_expresion','main.py',109),
  ('expresion -> expresion MAS expresion','expresion',3,'p_expresion','main.py',110),
  ('expresion -> expresion MENOS expresion','expresion',3,'p_expresion','main.py',111),
  ('expresion -> PARENT_A expresion PARENT_C','expresion',3,'p_expresion_par','main.py',118),
  ('vacio -> <empty>','vacio',0,'p_vacio','main.py',124),
]
